### ISSUE TITLE
UndefVarError: spot not defined

### ISSUE THREAD

**Issue by YuanZhuang18** [sisl/POMDPModelChecking.jl#12]
when I run to the code in blind_gridworld_example.jl
`policy = solve(solver, pomdp);`
there is a bug "UndefVarError: spot not define"
My packages' version is the same as the Manifiest.toml and Project.toml

**Comment by MaximeBouton** [comment]
which julia version are you using? 
Can you send the output of `] st` (in the julia REPL) ?

I cleaned the rock_sample.jl example recently, does this one work?

**Comment by YuanZhuang18** [comment]
I use the environment in example.jl.

> (examples) pkg> st
    Status `~/POMDP/POMDPModelChecking.jl/examples/Project.toml`
  [8bb6e9a1] BeliefUpdaters v0.2.1
  [159f3aea] Cairo v1.0.4
  [7f35509c] POMDPGifs v0.1.0
→ [abefb91b] POMDPModelChecking v0.0.0 [`../../dev/POMDPModelChecking`]
  [08074719] POMDPModelTools v0.3.1
  [355abbd5] POMDPModels v0.4.9
  [e0d0a172] POMDPSimulators v0.3.7
  [a93abf59] POMDPs v0.9.0
  [92933f4c] ProgressMeter v1.3.2
  [295af30f] Revise v2.7.3
  [de008ff0] RockSample v0.1.2
  [cef570c6] SARSOP v0.5.3
  [f11abc24] Spot v0.1.0
  [10745b16] Statistics 
┌ Warning: Some packages (indicated with a red arrow) are not downloaded, use `instantiate` to instantiate the current environment
└ @ Pkg.Display /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Display.jl:233

Then, I add POMDPModelChecking.jl by
 

> (examples) pkg>  add https://github.com/sisl/POMDPModelChecking.jl.git
  Updating git-repo `https://github.com/sisl/POMDPModelChecking.jl.git`
  Updating git-repo `https://github.com/sisl/POMDPModelChecking.jl.git`
 Resolving package versions...
 Installed LaTeXStrings ─ v1.2.0
  Updating `~/POMDP/POMDPModelChecking.jl/examples/Project.toml`
  [abefb91b] ~ POMDPModelChecking v0.0.0 [`../../dev/POMDPModelChecking`] ⇒ v0.0.0 #master (https://github.com/sisl/POMDPModelChecking.jl.git)
  Updating `~/POMDP/POMDPModelChecking.jl/examples/Manifest.toml`
  [6e34b625] ↑ Bzip2_jll v1.0.6+3 ⇒ v1.0.6+4
  [83423d85] ↑ Cairo_jll v1.16.0+4 ⇒ v1.16.0+5
  [324d7699] ↑ CategoricalArrays v0.8.1 ⇒ v0.8.3
  [da1fd8a2] ↑ CodeTracking v0.5.11 ⇒ v0.5.12
  [35d6a980] ↑ ColorSchemes v3.9.0 ⇒ v3.10.0
  [3da002f7] ↑ ColorTypes v0.10.8 ⇒ v0.10.9
  [5ae59095] ↑ Colors v0.12.3 ⇒ v0.12.4
  [34da2185] ↑ Compat v3.14.0 ⇒ v3.16.0
  [a81c6b42] ↑ Compose v0.9.0 ⇒ v0.9.1
  [a8cc5b0e] ↑ Crayons v4.0.3 ⇒ v4.0.4
  [a93c6f00] ↑ DataFrames v0.21.6 ⇒ v0.21.7
  [4b033969] ↑ DiscreteValueIteration v0.4.3 ⇒ v0.4.4
  [31c24e10] ↑ Distributions v0.23.9 ⇒ v0.23.12
  [2e619515] ↑ Expat_jll v2.2.7+4 ⇒ v2.2.7+5
  [c87230d0] ↑ FFMPEG v0.2.4 ⇒ v0.4.0
  [b22a6f82] + FFMPEG_jll v4.3.1+2
  [5789e2e9] ↑ FileIO v1.4.1 ⇒ v1.4.3
  [1a297f60] ↑ FillArrays v0.9.4 ⇒ v0.9.6
  [a3f928ae] ↑ Fontconfig_jll v2.13.1+12 ⇒ v2.13.1+13
  [d7e528f0] ↑ FreeType2_jll v2.10.1+3 ⇒ v2.10.1+4
  [559328eb] ↑ FriBidi_jll v1.0.5+4 ⇒ v1.0.5+5
  [78b55507] ↑ Gettext_jll v0.20.1+5 ⇒ v0.20.1+6
  [7746bdde] ↑ Glib_jll v2.59.0+2 ⇒ v2.59.0+3
  [3b182d85] ↑ Graphite2_jll v1.3.13+2 ⇒ v1.3.13+3
  [2e76f6c2] ↑ HarfBuzz_jll v2.6.1+5 ⇒ v2.6.1+9
  [a51ab1cf] + ICU_jll v67.1.0+1
  [682c06a0] ↑ JSON v0.21.0 ⇒ v0.21.1
  [aacddb02] ↑ JpegTurbo_jll v2.0.1+1 ⇒ v2.0.1+2
  [aa1ae85d] ↑ JuliaInterpreter v0.7.24 ⇒ v0.7.26
  [c1c5ebd0] + LAME_jll v3.100.0+2
  [dd4b983a] ↑ LZO_jll v2.10.0+1 ⇒ v2.10.0+2
  [b964fa9f] ↑ LaTeXStrings v1.1.0 ⇒ v1.2.0
  [dd192d2f] + LibVPX_jll v1.9.0+0
  [e9f186c6] ↑ Libffi_jll v3.2.1+2 ⇒ v3.2.1+3
  [d4300ac3] ↑ Libgcrypt_jll v1.8.5+2 ⇒ v1.8.5+3
  [7add5ba3] ↑ Libgpg_error_jll v1.36.0+1 ⇒ v1.36.0+2
  [94ce4f54] ↑ Libiconv_jll v1.16.0+5 ⇒ v1.16.0+6
  [4b2f31a3] ↑ Libmount_jll v2.34.0+1 ⇒ v2.34.0+2
  [89763e89] ↑ Libtiff_jll v4.1.0+0 ⇒ v4.1.0+1
  [38a345b3] ↑ Libuuid_jll v2.34.0+5 ⇒ v2.34.0+6
  [6f1432cf] ↑ LoweredCodeUtils v0.4.7 ⇒ v0.4.9
  [e1d29d7a] ↑ Missings v0.4.3 ⇒ v0.4.4
  [e7412a2a] + Ogg_jll v1.3.4+1
  [458c3c95] + OpenSSL_jll v1.1.1+5
  [91d4177d] + Opus_jll v1.3.1+2
  [bac558e1] ↑ OrderedCollections v1.3.0 ⇒ v1.3.1
  [2f80f16e] ↑ PCRE_jll v8.42.0+2 ⇒ v8.42.0+3
  [90014a1f] ↑ PDMats v0.10.0 ⇒ v0.10.1
  [abefb91b] ~ POMDPModelChecking v0.0.0 [`../../dev/POMDPModelChecking`] ⇒ v0.0.0 #master (https://github.com/sisl/POMDPModelChecking.jl.git)
  [36c8627f] ↑ Pango_jll v1.42.4+8 ⇒ v1.42.4+9
  [30392449] ↑ Pixman_jll v0.38.4+3 ⇒ v0.38.4+4
  [1fd47b50] ↑ QuadGK v2.4.0 ⇒ v2.4.1
  [71555da5] ↑ Reel v1.3.0 ⇒ v1.3.2
  [ae029012] ↑ Requires v1.0.1 ⇒ v1.0.3
  [2913bbd2] ↑ StatsBase v0.32.2 ⇒ v0.33.1
  [856f2bd8] + StructTypes v1.1.0
  [37f6aa50] ↑ TikzPictures v3.2.0 ⇒ v3.3.0
  [b8865327] ↑ UnicodePlots v1.2.0 ⇒ v1.3.0
  [02c8fc9c] ↑ XML2_jll v2.9.10+1 ⇒ v2.9.10+2
  [aed1982a] ↑ XSLT_jll v1.1.33+2 ⇒ v1.1.33+3
  [4f6342f7] ↑ Xorg_libX11_jll v1.6.9+2 ⇒ v1.6.9+3
  [0c0b7dd1] ↑ Xorg_libXau_jll v1.0.9+2 ⇒ v1.0.9+3
  [a3789734] ↑ Xorg_libXdmcp_jll v1.1.3+2 ⇒ v1.1.3+3
  [1082639a] ↑ Xorg_libXext_jll v1.3.4+2 ⇒ v1.3.4+3
  [ea2f1a96] ↑ Xorg_libXrender_jll v0.9.10+2 ⇒ v0.9.10+3
  [14d82f49] ↑ Xorg_libpthread_stubs_jll v0.1.0+1 ⇒ v0.1.0+2
  [c5fb5394] ↑ Xorg_xtrans_jll v1.4.0+1 ⇒ v1.4.0+2
  [83775a58] ↑ Zlib_jll v1.2.11+15 ⇒ v1.2.11+16
  [3161d3a3] ↑ Zstd_jll v1.4.5+0 ⇒ v1.4.5+1
  [0ac62f75] + libass_jll v0.14.0+3
  [f638f0a6] + libfdk_aac_jll v0.1.6+3
  [b53b4c65] ↑ libpng_jll v1.6.37+4 ⇒ v1.6.37+5
  [f27f6e37] + libvorbis_jll v1.3.6+5
  [1270edf5] + x264_jll v2020.7.14+1
  [dfaa095f] + x265_jll v3.0.0+2

There is an error.

> (examples) pkg> evaluation error starting at /Users/zhuang/POMDP/POMDPModelChecking.jl/examples/logging.jl:306
>   UndefVarError: #90#level not defined
> Stacktrace:
>  [1] #collect_args#60(::Bool, ::typeof(JuliaInterpreter.collect_args), ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:60
> while evaluating
> begin
>     #= /Users/zhuang/.julia/packages/Xorg_libXext_jll/1o4Gp/src/Xorg_libXext_jll.jl:43 =#
>     if best_platform === nothing
>         #= /Users/zhuang/.julia/packages/Xorg_libXext_jll/1o4Gp/src/Xorg_libXext_jll.jl:44 =#
>         #= /Users/zhuang/.julia/packages/Xorg_libXext_jll/1o4Gp/src/Xorg_libXext_jll.jl:44 =# @debug "Unable to load Xorg_libXext; unsupported platform $(triplet(platform_key_abi()))"
>     else
>         #= /Users/zhuang/.julia/packages/Xorg_libXext_jll/1o4Gp/src/Xorg_libXext_jll.jl:49 =#
>         best_platform = replace(best_platform, "arm-" => "armv7l-")
>         #= /Users/zhuang/.julia/packages/Xorg_libXext_jll/1o4Gp/src/Xorg_libXext_jll.jl:50 =#
>         include(joinpath(#= /Users/zhuang/.julia/packages/Xorg_libXext_jll/1o4Gp/src/Xorg_libXext_jll.jl:50 =# @__DIR__(), "wrappers", "$(best_platform).jl"))
>     end
> end
> in module Xorg_libXext_jll
> 
> 

Now, the result of "] st" is

> (examples) pkg> st
    Status `~/POMDP/POMDPModelChecking.jl/examples/Project.toml`
  [8bb6e9a1] BeliefUpdaters v0.2.1
  [159f3aea] Cairo v1.0.4
  [7f35509c] POMDPGifs v0.1.0
  [abefb91b] POMDPModelChecking v0.0.0 #master (https://github.com/sisl/POMDPModelChecking.jl.git)
  [08074719] POMDPModelTools v0.3.1
  [355abbd5] POMDPModels v0.4.9
  [e0d0a172] POMDPSimulators v0.3.7
  [a93abf59] POMDPs v0.9.0
  [92933f4c] ProgressMeter v1.3.2
  [295af30f] Revise v2.7.3
  [de008ff0] RockSample v0.1.2
  [cef570c6] SARSOP v0.5.3
  [f11abc24] Spot v0.1.0
  [10745b16] Statistics 

I run the code in  "blind_gridworld_example.jl"

> @everywhere begin 
    using Random
    using POMDPs
    using Spot
    using POMDPModelChecking
    import Cairo
    using POMDPModelTools
    using POMDPModels
    using POMDPSimulators
    using POMDPGifs
    using ProgressMeter
    using BeliefUpdaters
    using SARSOP
    using FileIO
    using JLD2
    include("../test/blind_gridworld.jl")
    # const LABELLED_STATES = Dict(GWPos(4,3) => :crash, GWPos(4,6)=>:crash,  GWPos(9,3)=>:a, GWPos(8,8)=>:b)    
    const LABELLED_STATES = Dict(GWPos(4,3) => :crash, GWPos(4,6)=>:crash)
    function POMDPModelChecking.labels(mdp::SimpleGridWorld, s, a)
        if haskey(LABELLED_STATES, s)
            return tuple(LABELLED_STATES[s])
        else
            return ()
        end
    end
    include("mc_simulation.jl")
end

there is an error occurs

> ERROR: UndefVarError: #normalize!#326 not defined
Stacktrace:[ Info: Precompiling POMDPModelChecking [abefb91b-a28c-5ab9-9bd9-026e532d7b0e]
 [1] macro expansion at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:60 [inlined]
 [2] maybe_evaluate_builtin(::JuliaInterpreter.Frame, ::Expr, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/builtins.jl:227
 [3] #evaluate_call_recurse!#64(::Bool, ::typeof(JuliaInterpreter.evaluate_call_recurse!), ::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:205
 [4] evaluate_call_recurse! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:202 [inlined]
 [5] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:389
 [6] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:524
 [7] signature(::Any, ::JuliaInterpreter.Frame, ::Any, ::Int64) at /Users/zhuang/.julia/packages/LoweredCodeUtils/u5hqt/src/packagedef.jl:134
 [8] signature(::Any, ::JuliaInterpreter.Frame, ::Int64) at /Users/zhuang/.julia/packages/LoweredCodeUtils/u5hqt/src/packagedef.jl:143
 [9] get_running_name(::Any, ::JuliaInterpreter.Frame, ::Int64, ::Symbol, ::Symbol) at /Users/zhuang/.julia/packages/LoweredCodeUtils/u5hqt/src/packagedef.jl:469
 [10] set_to_running_name!(::Any, ::Dict{Symbol,Symbol}, ::JuliaInterpreter.Frame, ::Dict{Symbol,LoweredCodeUtils.MethodInfo}, ::Dict{Symbol,Union{Bool, Symbol}}, ::Symbol, ::Symbol) at /Users/zhuang/.julia/packages/LoweredCodeUtils/u5hqt/src/packagedef.jl:316
 [11] rename_framemethods!(::Any, ::JuliaInterpreter.Frame, ::Dict{Symbol,LoweredCodeUtils.MethodInfo}, ::Array{NamedTuple{(:linetop, :linebody, :callee, :caller),Tuple{Int64,Int64,Symbol,Union{Bool, Symbol}}},1}, ::Dict{Symbol,Union{Bool, Symbol}}) at /Users/zhuang/.julia/packages/LoweredCodeUtils/u5hqt/src/packagedef.jl:349
 [12] rename_framemethods! at /Users/zhuang/.julia/packages/LoweredCodeUtils/u5hqt/src/packagedef.jl:364 [inlined]
 [13] #methods_by_execution!#17(::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Revise.methods_by_execution!), ::Any, ::Revise.CodeTrackingMethodInfo, ::Dict{Module,Array{Expr,1}}, ::Module, ::Expr) at /Users/zhuang/.julia/packages/Revise/BqeJF/src/lowered.jl:74
 [14] #methods_by_execution! at ./none:0 [inlined]
 [15] #eval_with_signatures#78 at /Users/zhuang/.julia/packages/Revise/BqeJF/src/Revise.jl:540 [inlined]
 [16] #eval_with_signatures at ./none:0 [inlined]
 [17] #instantiate_sigs!#79(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Revise.instantiate_sigs!), ::OrderedCollections.OrderedDict{Module,OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}}) at /Users/zhuang/.julia/packages/Revise/BqeJF/src/Revise.jl:548
 [18] instantiate_sigs! at /Users/zhuang/.julia/packages/Revise/BqeJF/src/Revise.jl:545 [inlined]
 [19] maybe_parse_from_cache!(::Revise.PkgData, ::String) at /Users/zhuang/.julia/packages/Revise/BqeJF/src/pkgs.jl:277
 [20] (::Revise.var"#39#40"{String})() at /Users/zhuang/.julia/packages/Revise/BqeJF/src/pkgs.jl:535
 [21] with_logstate(::Revise.var"#39#40"{String}, ::Base.CoreLogging.LogState) at ./logging.jl:395
 [22] with_logger at ./logging.jl:491 [inlined]
 [23] watch_manifest(::String) at /Users/zhuang/.julia/packages/Revise/BqeJF/src/pkgs.jl:514
 [24] (::Revise.TaskThunk)() at /Users/zhuang/.julia/packages/Revise/BqeJF/src/types.jl:229
[ Info: Skipping precompilation since __precompile__(false). Importing POMDPModelChecking [abefb91b-a28c-5ab9-9bd9-026e532d7b0e].
[ Info: Precompiling POMDPModelTools [08074719-1b2a-587c-a292-00f91cc44415]
[ Info: Precompiling POMDPPolicies [182e52fb-cfd0-5e46-8c26-fd0667c990f4]
[ Info: Precompiling DiscreteValueIteration [4b033969-44f6-5439-a48b-c11fa3648068]

And there is an reminder in the end of the executed code. As it cannot be copy, I screenshot it

> 
![1600653946385](https://user-images.githubusercontent.com/70354107/93728392-c5759780-fb8d-11ea-9739-6792ae8cc298.jpg)
![1600653954339](https://user-images.githubusercontent.com/70354107/93728393-c73f5b00-fb8d-11ea-82b6-7fdd0db3fda0.jpg)

**Comment by YuanZhuang18** [comment]
I think I have ran the rock_sample.jl succesfully. While when I tried to debug the program to see how it works, the spot UndefVar error occurred.

**Comment by MaximeBouton** [comment]
can you confirm the julia version and the platform? 
I will try to reproduce tomorrow. The error is at precompilation, I am suspecting something went wrong in the installation. 

If you are using the Project.toml and Manifest.toml that is on the repository you should not run `add https://github.com/sisl/POMDPModelChecking.jl.git` because as you can see in the stacktrace you posted it is bumping the version of many packages. 
In order to start with a clean environment, just replace the Manifest.toml (which has been modified by `add`) with the one that is on the repository.

**Comment by YuanZhuang18** [comment]
I use macOS Catalina 10.15.6
And the Julia version is 1.3.1

**Comment by YuanZhuang18** [comment]
I reproduce the spot bug as follow
![1](https://user-images.githubusercontent.com/70354107/93837002-9117df00-fc52-11ea-83f9-5e07b29534e3.jpg)
![2](https://user-images.githubusercontent.com/70354107/93837004-937a3900-fc52-11ea-8b85-9852c4bec064.jpg)

The error occurs at the bold line `automata = DeterministicRabinAutomata(solver.property)` in `src/model_checking_solver.jl`. The original line is 'policy = solve(solver, pomdp);' in 'examples/blind_gridworld_example.jl'

> function POMDPs.solve(solver::ModelCheckingSolver, problem::M) where M<:Union{MDP,POMDP}
>     verbose = solver.verbose
>     # parse formula first 
>     **automata = DeterministicRabinAutomata(solver.property)**
>     pmdp = nothing
>     sink_state = ProductState(first(states(problem)), -1)
>     if isa(problem, POMDP)
>         pmdp = ProductPOMDP(problem, automata, sink_state)
>     else
>         pmdp = ProductMDP(problem, automata, sink_state) # build product mdp x automata
>     end
>     if isempty(pmdp.accepting_states)
>         mec_time = @elapsed begin
>             accepting_states!(pmdp, verbose=verbose) # compute the maximal end components via a graph analysis
>             verbose ? println("Found ", length(pmdp.accepting_states), " accepting states") : nothing
>         end
>     end
>     println("MEC comp time: ", mec_time)
>     policy = solve(solver.solver, pmdp) # solve using your favorite method
>     return ModelCheckingPolicy(policy, pmdp, get_init_state_number(automata))
> end

I debug. The Error and Stacktrace are as follow

> ERROR: BoundsError: attempt to access 4-element Array{Any,1} at index [5]

> Stacktrace:
>  [1] getindex at ./array.jl:744 [inlined]
>  [2] build_compiled_call!(::Expr, ::Function, ::Core.CodeInfo, ::Int64, ::Int64, ::Array{Symbol,1}, ::Module) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/optimize.jl:344
>  [3] optimize!(::Core.CodeInfo, ::Method) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/optimize.jl:179
>  [4] #FrameCode#1(::Bool, ::Bool, ::Type{JuliaInterpreter.FrameCode}, ::Method, ::Core.CodeInfo) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/types.jl:101
>  [5] Type at ./none:0 [inlined]
>  [6] #prepare_framecode#35(::Bool, ::typeof(JuliaInterpreter.prepare_framecode), ::Method, ::Any) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/construct.jl:190
>  [7] (::JuliaInterpreter.var"#kw##prepare_framecode")(::NamedTuple{(:enter_generated,),Tuple{Bool}}, ::typeof(JuliaInterpreter.prepare_framecode), ::Method, ::Type) at ./none:0
>  [8] #prepare_call#38(::Bool, ::typeof(JuliaInterpreter.prepare_call), ::Any, ::Array{Any,1}) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/construct.jl:261
>  [9] #prepare_call at ./none:0 [inlined]
>  [10] #get_call_framecode#59(::Bool, ::typeof(JuliaInterpreter.get_call_framecode), ::Array{Any,1}, ::JuliaInterpreter.FrameCode, ::Int64) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/localmethtable.jl:63
>  [11] #get_call_framecode at ./none:0 [inlined]
>  [12] #evaluate_call_recurse!#64(::Bool, ::typeof(JuliaInterpreter.evaluate_call_recurse!), ::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:225
>  [13] evaluate_call_recurse! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:202 [inlined]
>  [14] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:389
>  [15] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:445
>  [16] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:579
>  [17] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:14
>  [18] finish_and_return! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:29 [inlined]
>  [19] #evaluate_call_recurse!#64(::Bool, ::typeof(JuliaInterpreter.evaluate_call_recurse!), ::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:240
>  ... (the last 7 lines are repeated 1 more time)
>  [27] evaluate_call_recurse! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:202 [inlined]
>  [28] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:389
>  [29] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:529
>  [30] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:579
>  [31] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:14
>  [32] finish_and_return! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:29 [inlined]
>  [33] #evaluate_call_recurse!#64(::Bool, ::typeof(JuliaInterpreter.evaluate_call_recurse!), ::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:240
>  [34] evaluate_call_recurse! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:202 [inlined]
>  [35] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:389
>  [36] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:445
>  [37] step_expr! at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/interpret.jl:579 [inlined]
>  [38] next_until!(::Any, ::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:95
>  [39] _next_line!(::Any, ::JuliaInterpreter.Frame, ::Bool, ::Int64, ::String) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:180
>  [40] next_line!(::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:175
>  [41] #debug_command#85(::Nothing, ::typeof(JuliaInterpreter.debug_command), ::Any, ::JuliaInterpreter.Frame, ::Symbol, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:433
>  [42] debug_command(::Any, ::JuliaInterpreter.Frame, ::Symbol, ::Bool) at /Users/zhuang/.julia/packages/JuliaInterpreter/CPmYX/src/commands.jl:415
>  [43] (::Atom.JunoDebugger.var"#54#56"{Bool,Bool,Bool})() at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:193
>  [44] evalscope(::Atom.JunoDebugger.var"#54#56"{Bool,Bool,Bool}) at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:386
>  [45] #startdebugging#53(::Bool, ::Bool, ::typeof(Atom.JunoDebugger.startdebugging), ::JuliaInterpreter.Frame, ::Bool) at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:151
>  [46] #startdebugging at ./none:0 [inlined]
>  [47] (::Base.var"#inner#2"{Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:istoplevel, :toggle_ui),Tuple{Bool,Bool}}},typeof(Atom.JunoDebugger.startdebugging),Tuple{JuliaInterpreter.Frame,Bool}})() at ./essentials.jl:712
>  [48] #invokelatest#1(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:istoplevel, :toggle_ui),Tuple{Bool,Bool}}}, ::typeof(Base.invokelatest), ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:713
>  [49] (::Base.var"#kw##invokelatest")(::NamedTuple{(:istoplevel, :toggle_ui),Tuple{Bool,Bool}}, ::typeof(Base.invokelatest), ::Function, ::JuliaInterpreter.Frame, ::Vararg{Any,N} where N) at ./none:0
>  [50] (::Atom.JunoDebugger.var"#48#51"{String,String,Bool,Int64})() at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:113
>  [51] hideprompt(::Atom.JunoDebugger.var"#48#51"{String,String,Bool,Int64}) at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/repl.jl:127
>  [52] #47 at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:84 [inlined]
>  [53] task_local_storage(::Atom.JunoDebugger.var"#47#50"{String,String,Bool,Int64}, ::Symbol, ::String) at ./task.jl:226
>  [54] debug_file(::String, ::String, ::String, ::Bool, ::Int64) at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:83
>  [55] debug_file(::String, ::String, ::String, ::Bool) at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/debugger/stepper.jl:81
>  [56] handlemsg(::Dict{String,Any}, ::String, ::Vararg{Any,N} where N) at /Users/zhuang/.julia/packages/Atom/ZeFbA/src/comm.jl:169

I can run this in RockSample
![3](https://user-images.githubusercontent.com/70354107/93837363-d4bf1880-fc53-11ea-982b-ed0c51c4d736.jpg)


The status as follow

> (POMDPModelChecking) pkg> st
> Project POMDPModelChecking v0.0.0
>     Status `~/POMDP/POMDPModelChecking.jl/Project.toml`
>   [8bb6e9a1] BeliefUpdaters v0.2.1
>   [35d6a980] ColorSchemes v3.10.0
>   [a81c6b42] Compose v0.9.1
>   [a0b5b9ef] Cxx v0.4.0
>   [4b033969] DiscreteValueIteration v0.4.4
>   [31c24e10] Distributions v0.23.12
>   [5789e2e9] FileIO v1.4.3
>   [033835bb] JLD2 v0.2.0
>   [093fc24a] LightGraphs v1.3.3
>   [7f35509c] POMDPGifs v0.1.0
>   [abefb91b] POMDPModelChecking v0.0.0
>   [08074719] POMDPModelTools v0.3.2
>   [355abbd5] POMDPModels v0.4.9
>   [182e52fb] POMDPPolicies v0.3.3
>   [e0d0a172] POMDPSimulators v0.3.8
>   [92e6a534] POMDPTesting v0.2.5
>   [a93abf59] POMDPs v0.9.1
>   [d96e819e] Parameters v0.12.1
>   [92933f4c] ProgressMeter v1.3.4
>   [3aa3ecc9] QMDP v0.1.4
>   [295af30f] Revise v2.7.6
>   [de008ff0] RockSample v0.1.2
>   [cef570c6] SARSOP v0.5.3
>   [f11abc24] Spot v0.1.0
>   [90137ffa] StaticArrays v0.12.4
>   [37e2e46d] LinearAlgebra 
>   [9a3f8284] Random 
>   [10745b16] Statistics 
>   [8dfed614] Test

**Comment by YuanZhuang18** [comment]
But when I debug the RockSample.jl, the error of 
`ERROR: BoundsError: attempt to access 4-element Array{Any,1} at index [5]` 
occur again.

**Comment by YuanZhuang18** [comment]
It’s very interesting. I found the bug is only occurred when the prop is
LTL“G !crash”.
I don’t know why.

Thanks for your reply.

**Comment by YuanZhuang18** [comment]
While it still cannot be debugged. 😂

**Comment by MaximeBouton** [comment]
I was able to reproduce locally and will try to fix it, you can follow the progress in #13

**Comment by YuanZhuang18** [comment]
I write down my experience. Maybe it can give you a little inspiration.
 I have copied all the packages' name and uuid in `examples/project.toml` into the `POMDPMODELCHECHING.jl/project.toml`  except the packages of Cario FileIO and JLD2(due to add them will cause error). The code works except the LTL "G !crash" and debug mode.

**Comment by MaximeBouton** [comment]
I found the bug in Spot.jl: 
this line in automata.jl was the culprit. 
```julia
!( @cxx lab.f->is(spot::op::Not) )
```
I can fix it by using `icxx` instead, I am writing test and I will tag a new version of Spot.jl

**Comment by MaximeBouton** [comment]
The bug in Spot has been fixed and a new version has been released (v0.1.1)

**Comment by MaximeBouton** [comment]
I merged some changes in the example and verified that the script `blind_gridworld.jl` ran locally, could you please let me know if it works for you with the new changes? I will close the issue then.

**Comment by YuanZhuang18** [comment]
Nope. I cannot instantiate the example environment.
The error is 
`ERROR: Package SARSOP_jll [e478675d-f996-546e-baa1-da59d9de2062] not found in a registry.`
 And I found that the spot version in Profect.toml is still v0.1.0

**Comment by YuanZhuang18** [comment]
Sorry. I just found the new version. And I will try and give you a response asap.

**Comment by YuanZhuang18** [comment]
I got an error
`(examples) pkg> instantiate
ERROR: Package POMDPXFiles [c6f6ee83-58c6-5336-a19f-2c76817e1af6] not found in a registry.`

I didn't find this registration in JuliaRegistries/General.

**Comment by MaximeBouton** [comment]
you need the JuliaPOMDP registry: `] registry add https://github.com/JuliaPOMDP/Registry`

**Comment by YuanZhuang18** [comment]
Yes. It works. Problem solved. Thank you.

**Comment by MaximeBouton** [comment]
thanks for reporting the bug!
